### ISSUE TITLE
Payout dropdown menu is cut off at the bottom

### ISSUE THREAD

**Issue by only-dev-time** [steemit/condenser#3931]
In smaller browser windows, the lower area of the payout dropdown menu is cut off:

![Screenshot 2024-12-13 230046](https://github.com/user-attachments/assets/b431883d-a5ff-4a79-abe4-e6c12aa0fe2f)

The menu is fully displayed on wider browser windows:

![Screenshot 2024-12-13 230306](https://github.com/user-attachments/assets/504201c8-ca54-45af-9190-4357bc0d6ce1)

**Comment by only-dev-time** [comment]
`overflow: hidden` was added with fix #3822 
```css
.App__content {
  margin-top: 1rem;
  overflow: hidden;
  margin-bottom: 60px;
  padding-bottom: 30px;
 
  @include MQ(M) {
      margin-bottom: 0;
  }
}
```
@ety001: is it still necessary?
I think it is no longer necessary, as the `VerticalMenu` no longer flows over the screen.

@the-gorilla-steem: What do you think? Could `overflow` be removed at class `App__content`?

Alternatively, `height` could also be specified. However, this would probably require a calculation.
